### ISSUE TITLE
[TRACKER] Make snapping, grid and transformation more consistent across 2D and 3D

### ISSUE THREAD

**Issue by MCrafterzz** [godotengine/godot-proposals#217]
This pr tracks enchancements to implement regarding transformation, snapping and grids for both myself and others to implement.

**3d features to port to 2d:**
- [x] Scale snap (pr: https://github.com/godotengine/godot/pull/33182)
- [x] Movement handles (pr: https://github.com/godotengine/godot/pull/33451)
- [ ] Transformation message, the little message in the bottom left corner that says for example: Translating: (0, 1, 0)
- [ ] Transform dialog, allow you to quickly move, rotate or scale the object with numbers instead of handles/drag (W.I.P pr: https://github.com/godotengine/godot/pull/37828)

**2d enhancements:**
- [x] Make the snap relative option affect rotation (pr: https://github.com/godotengine/godot/pull/36887)
- [x] Make the snap relative option affect scaling (pr: https://github.com/godotengine/godot/pull/37823)

**2d features to port to 3d:**
- [x] Infinite grids (pr: https://github.com/godotengine/godot/pull/28289)
- [ ] Configurable grid, spacing and offset
- [ ] Relative snap, enabled by default to keep current behaviour but adds the option for absolute snapping aka snapping to grid for movement, snapping the result for rotateting/scaling
- [ ] Rotation snap offset

Let me know what you think of these suggestions and if you would like to add any more and I'll try to implement those that the community likes. Thanks!

**Comment by Seel** [comment]
I'd love configurable grid and absolute snapping.

**Comment by Calinou** [comment]
> [ ] Configurable grid, spacing and offset

This is already available in 3D, but it's in the Editor Settings. We should move this to a per-scene setting (complemented with a default value for new scenes in the Project Settings). We should also add that project setting for the 2D editor.

**Comment by MCrafterzz** [comment]
> I'd love configurable grid and absolute snapping.

I'm gonna implement more stuff once 3.2 is out. Adding things now will just create conflicts :P

**Comment by MCrafterzz** [comment]
> [ ] Configurable grid, spacing and offset
> 
> This is already available in 3D, but it's in the Editor Settings. There are also less options available (no offset, no non-square grid). We should move this to a per-scene setting (complemented with a default value for new scenes in the Project Settings). We should also add that project setting for the 2D editor.

I had no idea those settings existed for 3d. Defiently felt like the wrong place. 2D already have those features though,

**Comment by MCrafterzz** [comment]
Is there anything that should be added/removed from the list?

**Comment by Jummit** [comment]
Tickbox lists can be done like this:
`- [ ]`
- [ ]

**Comment by Jummit** [comment]
Isn't the transform dialog implemented?

**Comment by fire** [comment]
Is it possible to separate the proposals? Separate proposals makes voting and explaining uses for each proposal easier.
