### ISSUE TITLE
[TRACKER] Animation general usability improvements

### ISSUE THREAD

**Issue by vyshliy** [godotengine/godot-proposals#6681]
### Describe the project you are working on

I'm working a lot with animation system of Godot on several 2D projects.

### Describe the problem or limitation you are having in your project

There are a lot of small usability issues in the animation creation process. Some of them are time consuming when repeating or getting around. To improve the experience of interacting with this side of the engine, some changes are needed.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The proposal main goal is to offer ideas to improve animation related usability in Godot 4.1 and later.
Tracker will be updated with links to related existing or new proposals and issues to track all progress in this area. 
Since this list was started many of issues was already improved in 4.0, so huge thanks to developers.

#### Animation Editor:
- [ ] Allow timeline zooming in AnimationPlayer without needing to hover over the time bar. #10399
- [x] Stretch selected frames visually in timeline #3532
- [ ] Add track type for animating Node (such as Skeleton2D) as whole within one track #1908
- [ ] Group by node takes a lot space. Change layout suggestion or make it more functional as previous suggestion
- [ ] Set keyframe value right in timeline by click #6683
- [ ] Show and control easing in timeline
- [ ] Show current frame close to current time when FPS mode selected
- [ ] Add mode to set automatic animation length based on last frame (optionally default) or button to manually set length where last frame
- [x] Play only selected part of animation in editor
- [ ] Set position in timeline during playback
- [ ] Convert curves animation to keyframes  #25801 (closed)  #392 https://github.com/godotengine/godot-proposals/issues/392#issuecomment-581088397
- [x] Filter tracks by node/properties name like in scene hierarchy https://github.com/godotengine/godot/pull/103130#issue-2869369175
- [ ] Add several tracks/keyframes when several nodes are selected (like top menu buttons does, but for all suitable properties in inspector) https://github.com/godotengine/godot/pull/92842#issue-2338647887
- [x] Copy / paste whole track between different nodes if track has same data type by context menu on property path (now its possible by copying tracks and renaming path) #3419
- [x] Copy / paste frames between different tracks by shortcuts if track has same data type #3419
- [ ] Add option to play audio backwards when animation play back
- [ ] Add ability to play track only when playing back / forward
- [ ] Double click on node in scene window shows select tracks of this node if exist
- [ ] Animation speed scale can affect all tracks including audio tracks and animation playback tracks
- [ ] Double click on frame place track time on this frame
- [ ] Make ping-pong looping option not looped too
- [ ] Select new animation track also inside scene tree, not only in popup menu
- [ ] Add easing in / out options to keyframe (instead of "Make Easing Selection"?)
- [ ] Zoom edited animation in editor relative to selected time, instead of animation begin

#### Curves Editor:
- [ ] Edit multiple frames in / out handle at once (like it works with position in v 4.0)
- [x] Add new keyframe to curve with balanced in/out handles by default to not distort existing track to much
- [ ] Show curve / keyframe editor when selected node uses this type of track in animation
- [x] Scale curve handles value proportionally on scaling track
- [ ] Edit value in inspector for all selected curve frames in curve editor same as keyframes editor
- [x] Return ability to scale curve editor in both dimensions. (Done. But shortcut not obvious and can't be found in 'shortcuts' menu)
- [x] Bezier auto zoom https://github.com/godotengine/godot-proposals/issues/7547#issue-1863660838 
- [ ] Bug - Adding keyframes as curve rotates all added nodes
- [ ] Add ability to animate PackedVector2Array with curves #8302

#### AnimationPlayer:
- [ ] Record button should record all properties while asking to add track  #6685
- [ ] Place record button to animation player #169
- [x] Copy / paste shortcut shouldn't work with scene hierarchy while Animation player selected #3475
- [x] Disable add track confirmation #54524

#### AnimationTree StateMachine:
- [ ] Select several transitions in node editor
- [ ] Edit all selected nodes in statemachine
- [ ] Play / pause button in one
- [ ] Return switch mode to StateMachine UI

#### Skeleton2D:
- [ ] Improved Polygon2D UV editor  #3791

#### AnimatedSprite:
- [ ] Don't switch from AnimationPlayer to AnimatedSprite when select AnimatedSprite
- [ ] Add convenient way to add AnimatedSprite frames to AnimationPlayer
- [ ] Creating AnimatedSprite with empty SpriteFrame resource by default
- [x] Select several sprite frames #1696
- [ ] Paste copied frame right after selected frame
- [ ] Set parameters to several nodes at once (autoplay for example)
- [ ] Add ability to set default FPS to SpriteFrame resource

#### Changes indirectly related to animation workflow:
- [ ] Connect signals to several objects at once
- [ ] NodePath modal not select text area by default
- [ ] Unchanged exported script props in open scenes saved even if in script it was changed
- [ ] Remove top panel of engine like in browser tabs
- [x] Copy / paste values of complex properties as vectors
- [ ] Light2D mask
- [ ] Add skew handler
- [ ] Godot asset lib not loaded sometimes
- [ ] Add script to selected nodes at once
- [ ] Paste copied nodes in several nodes at once
- [ ] Play sound file by double click on it (instead advanced import settings)
- [ ] Make sub resources unique on several nodes at once
- [ ] Make local several nodes at once
- [ ] Enable new installed plugin in dialog with successful installation
- [x] Filter nodes in tree by node type (fixed in 4.2)

#### Related Issues:
- [ ] Camera2D preview #7627
- [ ] 3.5 RC2 call method : methods doesn’t appears in method list immediately, only after project restart
- [ ] Animation not signal when finished if animation is looped
- [ ] Animation mix curves in one animation and simple in other give wrong behavior ??????
- [ ] Animation. Add keyframe with curve change existing rotation value with zero when use top bar to add keys
- [ ] Anim.current_animation doesn’t exist when anim.stop(false), while current_animation_length shows correct anim time
- [ ] Pasted tracks not changes existing same tracks in animation
- [ ] Adding rotation change current rotation of node
- [x] Add back ability to scale curves
- [ ] Crashes when work with animation library
- [ ] Crashes when delete last track of animation
- [ ] Crashes when animationTree is active
- [ ] Deleted sound still in AudioTrack on working machine, but not exist on exported version

### If this enhancement will not be used often, can it be worked around with a few lines of script?

The API of the engine does not make it easy to edit the animation editor using scripts. As well this is a usability improvement proposal.

### Is there a reason why this should be core and not an add-on in the asset library?

The essence of the tracker is to note core editor improvements. However, a consensus is possible on the implementation of some functionality as an asset.

**Comment by ToxicCrack** [comment]
I'm working on a VR D-Day Museum with many audio tracks and moving objects to them in sync. These AnimationPlayer improvements would speed up my workflow by a tremendous amount. Especially selecting multiple nodes and adding a keyframe for every single one of them (i.e. position).

**Comment by TokisanGames** [comment]
Thanks for putting together this list. It should also include bezier auto zoom https://github.com/godotengine/godot-proposals/issues/7547

And any points I made [here ](https://github.com/godotengine/godot-proposals/issues/3141#issuecomment-898944531) that did not get implemented

**Comment by vyshliy** [comment]
> It should also include bezier auto zoom #7547
Also encounter this all the time. Added to list

**Comment by Stealcase** [comment]
A Low-hanging fruit that would make my life a lot more pleasant:
- Make the property "Autoplay" in the AnimationPlayer available in the editor.

![image](https://github.com/godotengine/godot-proposals/assets/38126357/8971b922-e279-4144-9c79-693bf80d297b)


Why?
Because currently, if I want to just quickly add an animation player and play an animation on scene initialization, I have to add a script to the component! 
This does not spark joy for quick prototypes.

![image](https://github.com/godotengine/godot-proposals/assets/38126357/17be35fe-7e15-42ba-a3c5-d0c27d59260a)

**Comment by vyshliy** [comment]
> Make the property "Autoplay" in the AnimationPlayer available in the editor.

Why "autoplay on load" in the player doesn't work for you?

![Screenshot_1](https://github.com/godotengine/godot-proposals/assets/72736632/c5403dd8-104d-4ad4-bda3-d5829de7bda4)

**Comment by Stealcase** [comment]
> > Make the property "Autoplay" in the AnimationPlayer available in the editor.
> 
> Why "autoplay on load" in the player doesn't work for you?

I didn't know that was a thing! I feel silly now, thanks for the screenshot. 
I was looking for the parameter in the Inspector and couldn't find it, and the Class Documentation didn't mention it being visible in the Godot Editor, so I assumed it just had never been made an exposed property.

**Comment by tavurth** [comment]
> Stretch selected frames visually in timeline
Fixes https://github.com/godotengine/godot-proposals/issues/3937?

**Comment by vyshliy** [comment]
> > Stretch selected frames visually in timeline
> 
> Fixes #3937?

I think this is a proposal to freely scale frames for the current animation, as described in #3532. What you mentioned is different and now in the editor it is done by duplicating the animation and changing its scale to -1. The option you suggested seems to solve the problem of reflected animation for the animation tree more conveniently, although I think this should be in the editor core as a function of the animation tree node.

**Comment by mihe** [comment]
> Add several tracks/keyframes when several nodes are selected

I made an attempt at implementing this one, in [#92842](https://github.com/godotengine/godot/pull/92842), in case anyone here wants to take a look at it and/or provide some feedback.

I'm new to the animation side of the codebase (and animation in general to be honest) so the PR might need some minor alterations, assuming it's a viable change to begin with.

**Comment by vyshliy** [comment]
> I made an attempt at implementing this one, in [#92842](https://github.com/godotengine/godot/pull/92842), in case anyone here wants to take a look at it and/or provide some feedback.

Looks really good. This will save a lot of time during the animation process.

**Comment by yosimba2000** [comment]
I would like to request timeline zooming when cursor hovers over the timeline area 10399

**Comment by vyshliy** [comment]
> I would like to request timeline zooming when cursor hovers over the timeline area #10399

Added this to the list

**Comment by Arnklit** [comment]
I made a pull request for track filtering here. https://github.com/godotengine/godot/pull/103130

**Comment by vyshliy** [comment]
> I made a pull request for track filtering here. [godotengine/godot#103130](https://github.com/godotengine/godot/pull/103130)

Thank you!  I think this will help well with animation on laptops. Until now, it was a choice between the scene view and the animation player, which is quite crowded.

**Comment by Copperplate** [comment]
Two things I came across today with Bezier Curve tracks for the AnimationPlayer node:

1. The inability to add "bounce" or "elastic" interpolation (like we have in tweens).
2. The inability to box select the curve handles of keyframes, making it impossible to achieve uniform scaling with Bezier curves.

Both of these abilities exist in Blender's curve editor, and the latter is fundamental for any serious animation work, so that would truly be a great feature to have in Godot.

Thank you all for your excellent work on this program. :-)

**Comment by Anixias** [comment]
Something I encounter often is having an animation break in inherited scenes because I reordered nodes in the parent. Would be nice if it would automatically use the unique name ("%") feature for nodes that have that enabled. Manually entering "%" in the track name fixes the issue, but using the key icon on a property of that node adds a new relative path track instead of using the existing %-named track.

**Comment by BaconEggsRL** [comment]
> Two things I came across today with Bezier Curve tracks for the AnimationPlayer node:
> 
> 1. The inability to add "bounce" or "elastic" interpolation (like we have in tweens).
> 2. The inability to box select the curve handles of keyframes, making it impossible to achieve uniform scaling with Bezier curves.
> 
> Both of these abilities exist in Blender's curve editor, and the latter is fundamental for any serious animation work, so that would truly be a great feature to have in Godot.
> 
> Thank you all for your excellent work on this program. :-)

I've been investigating various interpolation modes for Tween and also AnimationPlayer.

In AnimationPlayer, you have Track Mode and Track Interpolation:
https://docs.godotengine.org/en/stable/tutorials/animation/introduction.html#id18

Track mode allows for either discrete or continuous animation.

Track interpolation is where I would expect to have more fine-tuned control over the interpolation between keyframes.
However it seems like this is only on a per-track basis.

You can also set the "Easing" property of the keyframe itself:
https://docs.godotengine.org/en/stable/tutorials/animation/introduction.html#edit-keyframes
No overshoot appears to be allowed though.

There is a proposal here to add additional easing options per keyframe:
https://github.com/godotengine/godot-proposals/issues/8791

The godot docs should probably show an example where you can right click the easing curve for more options.
This makes it much easier to work with, but I didn't see this illustrated in the docs (only in the GitHub issue.)
<img width="195" height="178" alt="Image" src="https://github.com/user-attachments/assets/9f3ccbbd-801c-4695-b234-734e6f395bcb" />

Selecting two keyframes allows you to set the easing between those two keyframes.
This adds on top of whatever easing is selected for the whole track.

I think these tools are already great; and it seems like there might be some opportunity to expand them and make them even more powerful.

Obviously we don't want to clutter the editor with a million options, but I think there may be an opportunity here to allow for custom interpolators (similar to PropertyTweener's [set_custom_interpolator](https://docs.godotengine.org/en/stable/classes/class_propertytweener.html#class-propertytweener-method-set-custom-interpolator), added in 2025.)

This could allow more options; both for the whole track and for individual animations between keyframes.
Not to self-promote, but an example of [what might be possible](https://store.godotengine.org/asset/baconeggsrl/easing-curve/).
